sudo: require
language: python
python:
  - "3.5"
  
install:
  - sudo pip3 install coveralls
  - python3 setup.py install
  
script:
  - pytest

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - ngh3053@gmail.com
    on_success: always
    on_failure: always