sudo: require
language: python
python:
  - "3.5"
  
install:
  - sudo apt-get install python3-pip
  - pip3 install pytest-cov==2.4.0
  - pip3 install coveralls==1.1
  
script:
  - py.test --cov ngh_func

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - ngh3053@gmail.com
    on_success: always
    on_failure: always
