language: python
python:
  - "3.5"
  
install:
  - python3 setup.py install
  
script:
  - pytest

notifications:
  email:
    recipients:
      - ngh3053@gmail.com
      - dollking@kookmin.ac.kr
    on_success: always
    on_failure: always